---
tags: [java, spring-boot, API]
Projeto: [logistic-center-challenge]
---
:spring_boot_version: 1.5.3.RELEASE
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot
Este guia foi feito para detalhar mais sobre a API do Desafio de Centro Logístico e mostrar como subi-la em seu Google Cloud Engine.

== O que é este branch?
Neste branch é encontrada a API que resolve o desafio do Centro Logístico.
include::https://github.com/CesarNog/desafioCentroLogistico-API/blob/master/Hands%20On%20-%20Desafio%20do%20centro%20logi%CC%81stico%202.0.pdf[]

== Do que você precisará para rodar esta API

:java_version: 1.8
:docker: last
:spring-boot: 1.5.4

== Como rodar a aplicação
Para rodar a aplicação, execute:

[subs="attributes"]
----
./gradlew build && java -jar build/libs/{project_id}-0.1.0.jar
----

Usando Maven, execute:

[subs="attributes"]
----
mvn package && java -jar target/{project_id}-0.1.0.jar
----

Você deve ver um resultado como este:

....
Let's inspect the beans provided by Spring Boot:
application
beanNameHandlerMapping
defaultServletHandlerMapping
dispatcherServlet
embeddedServletContainerCustomizerBeanPostProcessor
handlerExceptionResolver
helloController
httpRequestHandlerAdapter
messageSource
mvcContentNegotiationManager
mvcConversionService
mvcValidator
org.springframework.boot.autoconfigure.MessageSourceAutoConfiguration
org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$DispatcherServletConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat
org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration
org.springframework.boot.context.embedded.properties.ServerProperties
org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor
org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor
org.springframework.context.annotation.internalAutowiredAnnotationProcessor
org.springframework.context.annotation.internalCommonAnnotationProcessor
org.springframework.context.annotation.internalConfigurationAnnotationProcessor
org.springframework.context.annotation.internalRequiredAnnotationProcessor
org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration
propertySourcesBinder
propertySourcesPlaceholderConfigurer
requestMappingHandlerAdapter
requestMappingHandlerMapping
resourceHandlerMapping
simpleControllerHandlerAdapter
tomcatEmbeddedServletContainerFactory
viewControllerHandlerMapping
....

You can clearly see **org.springframework.boot.autoconfigure** beans. There is also a `tomcatEmbeddedServletContainerFactory`.

Check out the service.

....
$ curl localhost:8080
Greetings from Spring Boot!
....

== Adicionando casos de teste (Unit Tests)

You will want to add a test for the endpoint you added, and Spring Test already provides some machinery for that, and it's easy to include in your project.

Add this to your build file's list of dependencies:

[source,groovy]
----
include::complete/build.gradle[tag=tests]
----

Se estiver usando Maven, adicione isto em sua lista de dependências

[source,xml]
----
include::complete/pom.xml[tag=tests]
----


É fácil ver o status da aplicação:

----
$ curl localhost:8080/health
{"status":"UP","diskSpace":{"status":"UP","total":397635555328,"free":328389529600,"threshold":10485760}}}
----



From a different terminal window:
----
$ curl localhost:8080
Hello World!
----


== Sumário

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

