---
tags: [java, spring-boot, API]
Projeto: [logistic-center-challenge]
---
:spring_boot_version: 1.5.3.RELEASE
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot
Este guia foi feito para detalhar mais sobre a API do Desafio de Centro Logístico e mostrar como subi-la em seu Google Cloud Engine.

== O que é este branch?
Neste branch é encontrada a API que resolve o desafio do Centro Logístico.
include::https://github.com/CesarNog/desafioCentroLogistico-API/blob/master/Hands%20On%20-%20Desafio%20do%20centro%20logi%CC%81stico%202.0.pdf[]

== Do que você precisará para rodar esta API

:java_version: 1.8
:docker: last
:spring-boot: 1.5.4

== Como rodar a aplicação
Para rodar a aplicação, execute:

$ git clone https://github.com/CesarNog/desafioCentroLogistico-API.git
$ cd desafioCentroLogistico-API/api-java

- Rode a aplicação localmente:  
----
$ ./mvnw -DskipTests spring-boot:run
----

Você deve ver um resultado como este:

....
: 8080 (http)
Let's inspect the beans provided by Spring Boot:
actuatorMetricReader
application
applicationContextIdFilter
auditEventMvcEndpoint
auditEventRepository
auditEventsEndpoint
auditListener
autoConfigurationReportEndpoint
basicErrorController
beanNameHandlerMapping
beanNameViewResolver
beansEndpoint
characterEncodingFilter
commandLineRunner
configurationPropertiesReportEndpoint
conventionErrorViewResolver
counterBuffers
counterService
defaultServletHandlerMapping
defaultValidator
defaultViewResolver
diskSpaceHealthIndicator
diskSpaceHealthIndicatorProperties
dispatcherServlet
dispatcherServletRegistration
dumpEndpoint
duplicateServerPropertiesDetector
embeddedServletContainerCustomizerBeanPostProcessor
endpointHandlerMapping
endpointMBeanExporter
endpoints-org.springframework.boot.actuate.endpoint.EndpointProperties
endpoints.cors-org.springframework.boot.actuate.autoconfigure.EndpointCorsProperties
endpoints.health-org.springframework.boot.actuate.autoconfigure.HealthMvcEndpointProperties
endpoints.jmx-org.springframework.boot.actuate.autoconfigure.EndpointMBeanExportProperties
endpoints.metrics.filter-org.springframework.boot.actuate.autoconfigure.MetricFilterProperties
envInfoContributor
environmentEndpoint
environmentMvcEndpoint
error
errorAttributes
errorPageCustomizer
errorPageRegistrarBeanPostProcessor
faviconHandlerMapping
faviconRequestHandler
gaugeBuffers
gaugeService
greetingController
handlerExceptionResolver
healthAggregator
healthEndpoint
healthMvcEndpoint
heapdumpMvcEndpoint
helloController
hiddenHttpMethodFilter
httpPutFormContentFilter
httpRequestHandlerAdapter
infoEndpoint
jacksonObjectMapper
jacksonObjectMapperBuilder
jsonComponentModule
localeCharsetMappingsCustomizer
loggersEndpoint
loggersMvcEndpoint
management.health.status-org.springframework.boot.actuate.autoconfigure.HealthIndicatorProperties
management.info-org.springframework.boot.actuate.autoconfigure.InfoContributorProperties
management.trace-org.springframework.boot.actuate.trace.TraceProperties
managementContextResolver
managementServerProperties
managementServletContext
mappingJackson2HttpMessageConverter
mbeanExporter
mbeanServer
messageConverters
methodValidationPostProcessor
metricReaderPublicMetrics
metricWritersMetricExporter
metricsEndpoint
metricsFilter
metricsMvcEndpoint
multipartConfigElement
multipartResolver
mvcContentNegotiationManager
mvcConversionService
mvcEndpoints
mvcPathMatcher
mvcResourceUrlProvider
mvcUriComponentsContributor
mvcUrlPathHelper
mvcViewResolver
objectNamingStrategy
org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration
org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration$AuditEventRepositoryConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration$RequestMappingEndpointConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointMBeanExportAutoConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextFilterConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$EndpointWebMvcConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointWebMvcManagementContextConfiguration
org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration
org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$DiskSpaceHealthIndicatorConfiguration
org.springframework.boot.actuate.autoconfigure.InfoContributorAutoConfiguration
org.springframework.boot.actuate.autoconfigure.ManagementServerPropertiesAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration$MetricExportPropertiesConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration$StatsdConfiguration
org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration$FastMetricServicesConfiguration
org.springframework.boot.actuate.autoconfigure.PublicMetricsAutoConfiguration
org.springframework.boot.actuate.autoconfigure.PublicMetricsAutoConfiguration$TomcatMetricsConfiguration
org.springframework.boot.actuate.autoconfigure.TraceRepositoryAutoConfiguration
org.springframework.boot.actuate.autoconfigure.TraceWebFilterAutoConfiguration
org.springframework.boot.autoconfigure.AutoConfigurationPackages
org.springframework.boot.autoconfigure.condition.BeanTypeRegistry
org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration
org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration
org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration
org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
org.springframework.boot.autoconfigure.validation.DefaultValidatorConfiguration
org.springframework.boot.autoconfigure.validation.Jsr303ValidatorAdapterConfiguration
org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration
org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration
org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletConfiguration
org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DispatcherServletRegistrationConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration
org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat
org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$DefaultErrorViewResolverConfiguration
org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration
org.springframework.boot.autoconfigure.web.HttpEncodingAutoConfiguration
org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration
org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration$StringHttpMessageConverterConfiguration
org.springframework.boot.autoconfigure.web.JacksonHttpMessageConvertersConfiguration
org.springframework.boot.autoconfigure.web.JacksonHttpMessageConvertersConfiguration$MappingJackson2HttpMessageConverterConfiguration
org.springframework.boot.autoconfigure.web.MultipartAutoConfiguration
org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration
org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration
org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration$RestTemplateConfiguration
org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration
org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration
org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter
org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter$FaviconConfiguration
org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration
org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration$TomcatWebSocketConfiguration
org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor
org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.store
org.springframework.context.annotation.internalAutowiredAnnotationProcessor
org.springframework.context.annotation.internalCommonAnnotationProcessor
org.springframework.context.annotation.internalConfigurationAnnotationProcessor
org.springframework.context.annotation.internalRequiredAnnotationProcessor
org.springframework.context.annotation.internalScheduledAnnotationProcessor
org.springframework.context.event.internalEventListenerFactory
org.springframework.context.event.internalEventListenerProcessor
org.springframework.scheduling.annotation.SchedulingConfiguration
preserveErrorControllerTargetClassPostProcessor
propertySourcesPlaceholderConfigurer
requestContextFilter
requestMappingEndpoint
requestMappingHandlerAdapter
requestMappingHandlerMapping
resourceHandlerMapping
restTemplateBuilder
serverProperties
shutdownEndpoint
simpleControllerHandlerAdapter
spring.http.encoding-org.springframework.boot.autoconfigure.web.HttpEncodingProperties
spring.http.multipart-org.springframework.boot.autoconfigure.web.MultipartProperties
spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties
spring.jackson-org.springframework.boot.autoconfigure.jackson.JacksonProperties
spring.metrics.export-org.springframework.boot.actuate.metrics.export.MetricExportProperties
spring.mvc-org.springframework.boot.autoconfigure.web.WebMvcProperties
spring.resources-org.springframework.boot.autoconfigure.web.ResourceProperties
standardJacksonObjectMapperBuilderCustomizer
stringHttpMessageConverter
systemPublicMetrics
tomcatEmbeddedServletContainerFactory
tomcatPublicMetrics
traceEndpoint
traceRepository
viewControllerHandlerMapping
viewResolver
webRequestLoggingFilter
websocketContainerCustomizer
welcomePageHandlerMapping
2017-07-19 22:35:49.536  INFO 12521 --- [           main] hello.Application                        : Started Application in 10.614 seconds (JVM running for 23.206)
....

You can clearly see **org.springframework.boot.autoconfigure** beans. There is also a `tomcatEmbeddedServletContainerFactory`.

Check out the service.

Abra a API localmente em http://localhost:8080
  

....
$ curl localhost:8080
Greetings from Spring Boot!
....

== Adicionando casos de teste (Unit Tests)

You will want to add a test for the endpoint you added, and Spring Test already provides some machinery for that, and it's easy to include in your project.

Add this to your build file's list of dependencies:

[source,groovy]
----
include::complete/build.gradle[tag=tests]
----

Se estiver usando Maven, adicione isto em sua lista de dependências

[source,xml]
----
include::complete/pom.xml[tag=tests]
----


É fácil ver o status da aplicação:

----
$ curl localhost:8080/health
{"status":"UP","diskSpace":{"status":"UP","total":397635555328,"free":328389529600,"threshold":10485760}}}
----



From a different terminal window:
----
$ curl localhost:8080
Hello World!
----


== Sumário

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

